# This is a basic workflow to help you get started with Actions
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false
  
jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest

    steps:  
      - name: Pass the received secret to an action
        uses: ./.github/MariiaS3/MariiaS3
        with:
          token: ${{ secrets.TOKEN_README }}



